services:
  backend:
    build: ./backend
    expose:
      - "3000"
    volumes:
      - backend_data:/data
      - avatar_image:/data/avatar
      - ./backend/db/public/avatar.png:/data/avatar/avatar.png:ro
    networks:
      - app_network
    environment:
      - DATABASE_URL=/data/database.db
    env_file:
      - .env

  nginx:
    build: ./nginx
    ports:
      - "8443:443"  # Exposer le port 443 de l'hôte vers le port 80 du conteneur
    volumes:
      - ./frontend:/usr/share/nginx/html  # Cette ligne est correcte, monte le dossier frontend vers le bon chemin
      - avatar_image:/data/avatar
      - ./backend/db/public/avatar.png:/data/avatar/avatar.png:ro
    depends_on:
      - backend
    networks:
      - app_network
    environment:
      - BACKEND_URL=http://backend:3000
      - FRONTEND_URL=https://${LOCAL_IP}:8443
    env_file:
      - .env

networks:
  app_network:
    driver: bridge

volumes:
  backend_data:
  avatar_image:

