services:
  backend:
    build: ./backend
    expose:
      - "3000"
    volumes:
      - backend_data:/data
      - avatar_image:/data/avatar
      - ./backend/db/public/avatar.png:/data/avatar/avatar.png:ro
    networks:
      - app_network
    environment:
      - DATABASE_URL=/data/database.db
    env_file:
      - .env

  nginx:
    build: ./nginx
    ports:
      - "8443:443"  # Exposer le port 443 de l'hôte vers le port 80 du conteneur
    volumes:
      - ./frontend:/usr/share/nginx/html
      - avatar_image:/data/avatar
      - ./backend/db/public/avatar.png:/data/avatar/avatar.png:ro
    depends_on:
      - backend
    networks:
      - app_network
    environment:
      - BACKEND_URL=http://backend:3000
      - FRONTEND_URL=${FRONTEND_URL}
    env_file:
      - .env

  ngrok:
    image: ngrok/ngrok:latest
    command: http https://nginx:443 --domain=swan-genuine-cattle.ngrok-free.app
    depends_on:
      - nginx
    networks:
      - app_network
    environment:
      - NGROK_AUTHTOKEN=2wzc20BXk5JD6T6MybEz4MsF9qA_41Mmprgxr9Cvn9EpTGc7t
    ports:
    - "4040:4040" 

networks:
  app_network:
    driver: bridge

volumes:
  backend_data:
  avatar_image:

